# nixpacks.toml
[phases.setup]
nixPkgs = ["chromium", "chromedriver"]

[phases.install]
cmds = [
    "echo 'CHROME_BIN=/nix/var/nix/profiles/default/bin/chromium' >> .env",
    "echo 'CHROMEDRIVER_PATH=/nix/var/nix/profiles/default/bin/chromedriver' >> .env"
]

[variables]
CHROME_BIN = "/nix/var/nix/profiles/default/bin/chromium"
CHROMEDRIVER_PATH = "/nix/var/nix/profiles/default/bin/chromedriver"
